const employees = [
  {
    id: 1,
    firstName: "Ravi",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Complete Monthly Report",
        description: "Prepare and submit the monthly sales report.",
        date: "2024-10-20",
        category: "Reporting",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Organize Files",
        description: "Sort and organize departmental files.",
        date: "2024-10-18",
        category: "Organization",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Client Call",
        description: "Discuss project requirements with the client.",
        date: "2024-10-22",
        category: "Client Relations",
      },
    ],
    taskCount: { active: 2, newTask: 1, completed: 1, failed: 0 },
  },
  {
    id: 2,
    firstName: "Anjali",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Client Follow-up",
        description: "Follow up with client on project updates.",
        date: "2024-10-21",
        category: "Client Relations",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Documentation Update",
        description: "Update internal documentation for new processes.",
        date: "2024-10-18",
        category: "Documentation",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Project Proposal",
        description: "Draft proposal for upcoming project.",
        date: "2024-10-23",
        category: "Planning",
      },
    ],
    taskCount: { active: 2, newTask: 2, completed: 1, failed: 0 },
  },
  {
    id: 3,
    firstName: "Vikram",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Inventory Check",
        description: "Verify inventory status for all products.",
        date: "2024-10-19",
        category: "Inventory",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "New Client Outreach",
        description: "Reach out to potential clients.",
        date: "2024-10-20",
        category: "Client Relations",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Internal Training",
        description: "Attend training on new software.",
        date: "2024-10-17",
        category: "Training",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Website Maintenance",
        description: "Fix bugs on the website.",
        date: "2024-10-20",
        category: "Development",
      },
    ],
    taskCount: { active: 3, newTask: 1, completed: 1, failed: 0 },
  },
  {
    id: 4,
    firstName: "Pooja",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Market Analysis",
        description: "Conduct market analysis on competitor strategies.",
        date: "2024-10-20",
        category: "Research",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Budget Report",
        description: "Analyze previous quarter's budget.",
        date: "2024-10-18",
        category: "Finance",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Prepare Presentation",
        description: "Prepare presentation for team meeting.",
        date: "2024-10-22",
        category: "Meetings",
      },
    ],
    taskCount: { active: 2, newTask: 1, completed: 1, failed: 0 },
  },
  {
    id: 5,
    firstName: "Kiran",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Order Supplies",
        description: "Order necessary supplies for next month.",
        date: "2024-10-21",
        category: "Inventory",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Supplier Meeting",
        description: "Meet with supplier to discuss new products.",
        date: "2024-10-21",
        category: "Supplier Relations",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Warehouse Audit",
        description: "Complete audit of warehouse inventory.",
        date: "2024-10-19",
        category: "Audit",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Customer Service Training",
        description: "Attend training to improve customer service skills.",
        date: "2024-10-23",
        category: "Training",
      },
    ],
    taskCount: { active: 3, newTask: 1, completed: 1, failed: 0 },
  },
];

const admin = [
  {
    id: 1,
    firstName: "Suresh",
    email: "admin@example.com",
    password: "123",
  },
];

export function setLocalStorage() {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
}

export function getLocalStorage() {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
}
